/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package client

import com.cloudant.client.api.ClientBuilder
import com.cloudant.client.api.CloudantClient
import com.cloudant.client.api.query.Expression
import com.cloudant.client.api.query.QueryBuilder
import com.cloudant.client.api.query.QueryResult
import java.net.URL

data class Artist(
	val ConstituentID: Number,
	val DisplayName: String,
	val ArtistBio: String,
	val Nationality: String,
	val Gender: String,
	val BeginDat: Number,
	val EndDate: Number,
	val Wiki_QID: String,
	val ULAN: String
)

class App {

	fun getClient(): CloudantClient {
		return ClientBuilder.url(URL("http://localhost:5984")).build()
	}

	fun search(client: CloudantClient) {

		val artists = client.database("artists", false)
		val found: Artist? = artists.find(Artist::class.java, "4609")
		println("lookup by ID: 4609")
		println(found?.DisplayName)

		val queryResult: QueryResult<Artist> =
			artists.query(QueryBuilder(Expression.regex("DisplayName", ".*Pablo.*")).build(), Artist::class.java)
		println("query result: DisplayName matching /.*Pablo.*/")
		queryResult.docs.forEach { artist -> println(artist.DisplayName) }

	}
}

fun main() {
	App()
		.run {
			search(getClient())
		}
}
