/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package client

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {

	@Test
	fun pouchDbIsRunning() {
		val client = App().getClient()
		assertNotNull(client.allDbs, "artist and artwork db not available")
	}

	@Test
	fun searchForArtist() {
		val client = App().getClient()
		val artists = client.database("artists", false)
		val found: Artist = artists.find(Artist::class.java, "4609")
		assertNotNull(found, "artist not found")
	}
}
